---
params: 
  report_title: A/B Test Analysis
  data: NULL #./data/AB Test Analysis/events_raw_20170703155930.RData
  query: NULL 
  start_date: 20170630 # inclusive
  end_date: 20170707 # exclusive
  TSS2 revision number: 16909631
  wiki: enwiki
  test group names: [explore_similar_control, explore_similar_test]
  event_action: NULL #[searchResultPage, click, esclick, hover-on, hover-off]
  event_source: fulltext
title: "`r params$report_title`"
date: '`r Sys.Date()`'
output: html_document
---

```{r sql_setup}
# SQL setup. For local test only
library(RMySQL)
con <- dbConnect(MySQL(), host = "127.0.0.1", group = "client", dbname = "log", port = 3307)
```

```{r fetch_data, echo=FALSE}
query <- paste0("SELECT
  timestamp,
  event_uniqueId AS event_id,
  event_mwSessionId,
  event_pageViewId AS page_id,
  event_searchSessionId AS session_id,
  event_subTest AS `group`,
  wiki,
  MD5(LOWER(TRIM(event_query))) AS query_hash,
  event_action AS event,
  CASE
    WHEN event_position < 0 THEN NULL
    ELSE event_position
    END AS event_position,
  CASE
    WHEN event_action = 'searchResultPage' AND event_hitsReturned > 0 THEN 'TRUE'
    WHEN event_action = 'searchResultPage' AND event_hitsReturned = 0 THEN 'FALSE'
    ELSE NULL
    END AS `some same-wiki results`,
  event_hitsReturned AS n_results,
  event_scroll,
  event_checkin,
  event_extraParams,
  event_msToDisplayResults AS load_time,
  event_searchToken AS search_token,
  userAgent AS user_agent
FROM TestSearchSatisfaction2_", params$`TSS2 revision number`, "\n",
"WHERE LEFT(timestamp, 8) >= '", params$start_date, "' AND LEFT(timestamp, 8) < '", params$end_date, "' \n",
ifelse(is.null(params$wiki), "", paste0("  AND wiki IN('", paste(params$wiki, collapse = "', '"), "') \n")),
ifelse(is.null(params$`test group names`), "", paste0("  AND event_subTest IN('", paste(params$`test group names`, collapse = "', '"), "') \n")),
ifelse(is.null(params$event_action), "", paste0("  AND event_action IN('", paste(params$event_action, collapse = "', '"), "') \n")),
ifelse(is.null(params$event_source), "", paste0("  AND event_source IN('", paste(params$event_source, collapse = "', '"), "') \n")),
"  AND (
   (event_action = 'searchResultPage' AND event_hitsReturned IS NOT NULL AND event_msToDisplayResults IS NOT NULL)
   OR
   (event_action = 'click' AND event_position IS NOT NULL AND event_position > -1)
   OR
   (event_action = 'visitPage' AND event_pageViewId IS NOT NULL)
   OR
   (event_action = 'checkin' AND event_checkin IS NOT NULL AND event_pageViewId IS NOT NULL)
   OR
   (event_action = 'iwclick' AND event_position IS NOT NULL AND event_position > -1)
   OR
   (event_action = 'ssclick' AND event_position IS NOT NULL AND event_position > -1)
   OR event_action = 'esclick'
   OR event_action = 'hover-on' OR event_action = 'hover-off'
   );"
)
if (!is.null(params$query)) {
  query <- params$query
}
if (is.null(params$data)){
  events_raw <- wmf::mysql_read(query, "log")
  # Save raw events data
  if (!dir.exists(file.path("data", gsub(.Platform$file.sep, "", params$report_title)))) {
    dir.create(file.path("data", gsub(.Platform$file.sep, "", params$report_title)), recursive = TRUE)
  }
  save(events_raw, file = file.path("data", gsub(.Platform$file.sep, "", params$report_title), paste0("events_raw_", gsub("[^0-9]", "", Sys.time()), ".RData")))
  print_query <- TRUE
} else{
  if (tools::file_ext(params$data) == "RData"){
    load(params$data)
  } else{
    events_raw <- data.table::fread(input = params$data, data.table = FALSE)
  }
  print_query <- FALSE
}
```

`r if(print_query){"The SQL query is: "}`
```{sql, eval = FALSE, code = query, echo = print_query}
```

## Data Cleansing
```{r data_process, echo =FALSE, warning=FALSE}
if ("events_raw" %in% ls()) events <- events_raw

# Events may be duplicated
events <- events %>%
  mutate(timestamp = lubridate::ymd_hms(timestamp),
         date = as.Date(timestamp)) %>%
  dplyr::arrange(session_id, event_id, timestamp) %>%
  dplyr::distinct(session_id, event_id, .keep_all = TRUE)
print(paste0("Deleted ", nrow(events_raw) - nrow(events), " duplicated events."))

# SERP De-duplication
SERPs <- events %>%
  dplyr::filter(event == "searchResultPage") %>%
  dplyr::select(c(session_id, page_id, query_hash, search_token)) %>%
  dplyr::group_by(session_id, query_hash) %>%
  dplyr::mutate(serp_id = page_id[1], cirrus_id = search_token[1]) %>%
  dplyr::ungroup() %>%
  dplyr::select(c(page_id, serp_id, cirrus_id))
events <- events %>%
  dplyr::left_join(SERPs, by = "page_id"); rm(SERPs)

# Remove events without SERP asscociated
n_evnt <- nrow(events)
events <- events %>%
  dplyr::filter(!(is.na(serp_id) & !(event %in% c("visitPage", "checkin")))) %>% # remove orphan click
  dplyr::group_by(session_id) %>%
  dplyr::filter("searchResultPage" %in% event) %>% # remove orphan "visitPage" and "checkin"
  dplyr::ungroup()
print(paste0("Removed ", n_evnt - nrow(events), " orphan (SERP-less) events.")); rm(n_evnt)

# Remove sessions falling into multiple test groups
temp <- events %>% group_by(session_id) %>% summarise(unique_group = length(unique(group)) == 1)
print(paste0("Remove ", sum(!temp$unique_group), " sessions falling into multiple test groups."))
events <- events %>% filter(session_id %in% temp$session_id[temp$unique_group]); rm(temp)

# Aggregate by search
searches <- events %>%
  dplyr::filter(!(is.na(serp_id))) %>% # remove visitPage and checkin events
  dplyr::arrange(date, session_id, serp_id, timestamp) %>%
  dplyr::group_by(group, wiki, session_id, serp_id) %>%
  dplyr::summarize(timestamp = timestamp[1],
                   `got same-wiki results` = any(`some same-wiki results`),
                   engaged = any(event != "searchResultPage") || length(unique(page_id[event == "searchResultPage"])) > 1,
                   `same-wiki clickthrough` = "click" %in% event,
                   `other clickthrough` = sum(grepl("click", event) & event != "click"),
                   `no. same-wiki results clicked` = length(unique(event_position[event == "click"])),
                   `first clicked same-wiki results position` = ifelse(`same-wiki clickthrough`, event_position[event == "click"][1], NA), # event_position is 0-based
                   `Query score (F=0.1)` = query_score(event_position, 0.1),
                   `Query score (F=0.5)` = query_score(event_position, 0.5),
                   `Query score (F=0.9)` = query_score(event_position, 0.9)) %>%
  dplyr::ungroup()

# Aggregate by visited page (after clickthrough)
visitPage_action <- "visitPage" %in% unique(events$event) # users may not select "visitPage" and "checkin" event in query
if (visitPage_action){
  visitedPages <- events %>%
    dplyr::arrange(date, session_id, page_id, timestamp) %>%
    dplyr::group_by(group, wiki, session_id, page_id) %>%
    dplyr::filter("visitPage" %in% event) %>% # keep only checkin and visitPage action
    dplyr::summarize(timestamp = timestamp[1],
                     dwell_time = ifelse("checkin" %in% event, max(event_checkin, na.rm = T), 0),
                     scroll = sum(event_scroll) > 0) %>%
    dplyr::ungroup()
  visitedPages$dwell_time[is.na(visitedPages$dwell_time)] <- 0
  }
```

## Data Summary

### Test summary: 
```{r test_summary, echo=FALSE}
dplyr::data_frame(
  Days = length(unique(events$date)),
  Events = nrow(events),
  Sessions = length(unique(events$session_id)),
  `Page IDs` = length(unique(events$page_id)),
  `SERP events` = sum(events$event == "searchResultPage"),
  `Unique search queries` = length(unique(paste(events$session_id, events$query_hash))),
  SERPs = length(unique(events$serp_id[!is.na(events$serp_id)])),
  `Same-wiki clicks` = sum(events$event == "click"),
  `Other clicks (sister search etc.)` = sum(grepl("click", events$event) & events$event != "click")
) %>% knitr::kable()
```

### Number of events:
```{r event_count, echo=FALSE}
events %>%
  group_by(group, wiki, event) %>%
  tally %>%
  knitr::kable()
```

### Number of searches:
```{r searches_summary, echo=FALSE}
searches %>%
  group_by(`Test group` = group, wiki) %>%
  summarize(`Search sessions` = length(unique(session_id)), `Searches recorded` = n()) %>% ungroup %>% {
    rbind(., tibble(
      `wiki` = "All Wikis",
      `Test group` = "Total",
      `Search sessions` = sum(.$`Search sessions`),
      `Searches recorded` = sum(.$`Searches recorded`)
    ))
  } %>%
  mutate(`Search sessions` = prettyNum(`Search sessions`, big.mark = ","),
         `Searches recorded` = prettyNum(`Searches recorded`, big.mark = ",")) %>%
  knitr::kable()
```

### Number of searches with *n* result(s) returned: 
```{r n_results_summary, echo=FALSE}
events %>%
  dplyr::filter(event == "searchResultPage") %>%
  dplyr::mutate(results = dplyr::if_else(n_results >= 5, "5+ results", paste(n_results, "result(s)"))) %>%
  dplyr::group_by(group, results) %>%
  dplyr::summarize(searches = length(unique(serp_id[!is.na(serp_id)]))) %>%
  tidyr::spread(results, searches) %>%
  knitr::kable()
```

`r if(visitPage_action){"### Number of visited pages: "}`
```{r visitPage_summary, eval = visitPage_action, echo = FALSE}
visitedPages %>%
  dplyr::group_by(`Test group` = group, wiki) %>%
  dplyr::summarize(`Visited pages` = length(unique(page_id))) %>%
  dplyr::ungroup() %>% {
    rbind(., tibble(
      `wiki` = "All Wikis",
      `Test group` = "Total",
       `Visited pages` = sum(.$`Visited pages`)
    ))
  } %>%
  dplyr::mutate(`Visited pages` = prettyNum(`Visited pages`, big.mark = ",")) %>%
  knitr::kable()
```

## Test Metrics

### Same-wiki Zero Results Rate

```{r zrr, echo=FALSE}
searches %>%
  dplyr::group_by(group, wiki) %>%
  dplyr::summarise(zero = sum(!`got same-wiki results`), n_search = n()) %>%
  dplyr::do(binom::binom.bayes(x = .$zero, n = .$n_search, conf.level = 0.95)) %>%
  knitr::kable()
```

### Same-wiki Engagement
```{r engagement, echo=FALSE}
samewiki_ctr <- searches %>%
  dplyr::filter(`got same-wiki results` == TRUE) %>%
  dplyr::group_by(group, wiki) %>%
  dplyr::summarize(clickthroughs = sum(`same-wiki clickthrough`), n_search = n()) %>%
  dplyr::ungroup() %>%
  cbind(
    as.data.frame(binom:::binom.bayes(x = .$clickthroughs, n = .$n_search, conf.level = 0.95))
  )
samewiki_ctr %>% knitr::kable()
```

```{r engagement_OR, echo=FALSE, results='asis', include=TRUE}
control_group <- grep("control", params$`test group names`, value = TRUE)
test_group <- setdiff(params$`test group names`, control_group)

for (this_group in test_group){
   cat("####", control_group, " vs. ", this_group, " \n")
   samewiki_or <- samewiki_ctr %>%
     dplyr::filter(group %in% c(control_group, this_group)) %>%
     dplyr::arrange(wiki, desc(group)) %>%
     dplyr::group_by(wiki) %>%
     dplyr::do(BCDA::tidy(BCDA::beta_binom(.$x, .$n), interval_type = "HPD")) %>%
     dplyr::ungroup() %>%
     as.data.frame()
   print(knitr::kable(samewiki_or))
   cat("\n")
 }
```

### First Clicked Result’s Position
```{r first_clicked, echo=FALSE}
first_clicked <- searches %>%
  dplyr::filter(`got same-wiki results` & `same-wiki clickthrough` & !is.na(`first clicked same-wiki results position`)) %>%
  dplyr::mutate(`first clicked result's position` = ifelse(`first clicked same-wiki results position` < 4, safe_ordinals(`first clicked same-wiki results position` + 1), "5th or higher")) %>%
  dplyr::group_by(group, wiki, `first clicked result's position`) %>%
  dplyr::tally() %>%
  dplyr::mutate(total = sum(n)) %>%
  dplyr::ungroup()
first_clicked %>%
  cbind(
    as.data.frame(binom:::binom.bayes(.$n, n = .$total, conf.level = 0.95))
  ) %>%
  knitr::kable()
```
